# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
parameters:
- name: Branch
  displayName: Branch to Deploy
  type: string
  default: Develop
  values:
    - Develop
    - main
variables:
  branchName: ${{ parameters.Branch }}

# trigger:
# - main

pool:
  vmImage: windows-latest
resources:
  repositories:
    - repository: newproject01
      type: github
      name: infy1501/newproject01
      endpoint: infy1501
      ref: refs/heads/$(branchName)
      
stages:
- stage:
  jobs:
  - job:
    steps:
      
    - task: PowerShell@2
      inputs:
        filePath: 'newps.ps1'


